#!/bin/sh
#
# PROVIDE: specter
# REQUIRE: NETWORKING
# KEYWORD: shutdown

export PATH="/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin"

. /etc/rc.subr

name="specter"
rcvar="${name}_enable"

load_rc_config "${name}"

: ${specter_enable:="NO"}
: ${specter_user:="@SPECTER_USER@"}
: ${specter_config:="@SPECTER_CONF@"}
: ${specter_socket:="/var/run/specter/specter.sock"}

procname="@SPECTER_BIN@"
pidfile="/var/run/${name}.pid"
logfile="/var/log/${name}.log"

start_precmd="specter_precmd"
specter_cmd="${procname} run --config ${specter_config} --socket ${specter_socket}"

command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} -o ${logfile} -u ${specter_user} ${specter_cmd}"
extra_commands="reload"

specter_precmd()
{
	install -d -o "${specter_user}" -m 0700 "${specter_socket%/*}"
}

run_rc_command "$1"
