[graph]
all-features = true
exclude-dev  = true

[bans]
multiple-versions = "warn"

deny = [
  { name = "tokio" },
  { name = "tokio-util" },
  { name = "async-std" },
  { name = "mio" },
  { name = "polling" },
  { name = "smol" },
  { name = "futures-util" },
  { name = "libc", wrappers = [
    "specter-actuator",
    "specter-sensor",
    "errno",
    "nix",
    "signal-hook",
    "signal-hook-registry",
  ] },
  { name = "nix", wrappers = ["specter-sensor", "specter-actuator"] },
  { name = "specter-engine",   wrappers = ["specter-bin"] },
  { name = "specter-sensor",   wrappers = ["specter-bin"] },
  { name = "specter-actuator", wrappers = ["specter-bin"] },
]

[licenses]
allow = [
  "MIT", "Apache-2.0", "Unicode-3.0", "Zlib",
]
