//! Identity tiers and engine correlation tokens.
//!
//! Two families share this module, each with its own discipline:
//!
//! - **Slotmap keys.** [`ResourceId`], [`ProfileId`], [`SubId`],
//!   [`PromoterId`] are generational handles minted by
//!   [`slotmap::SlotMap`]; a stale id looks up to `None`. Reused slot
//!   indices carry distinct generations, so equality is exact identity
//!   over the slot's lifetime, not over the underlying index.
//! - **Monotonic correlation tokens.** [`TimerId`], [`CorrelationId`],
//!   [`ProbeCorrelation`] are plain `u64` wrappers minted by the
//!   engine's `MonotonicCounter`; they pair an engine emission with the
//!   external actor's echo (timer fire, effect completion, probe
//!   response) over the engine's lifetime. They are not slotmap keys —
//!   the per-mint state lives elsewhere (the engine's `TimerHeap`,
//!   `ProbeChannel`, or actuator-side coalesce state), and a cancelled
//!   or completed token is not reusable, only distinguishable.
//!
//! The monotonic family is generated by the module-local
//! [`monotonic_id!`] macro so the three tokens share one shape: a
//! private `u64` field, a derive set tuned for use as map / heap keys,
//! a [`From<u64>`] mint surface, and an `as_u64` accessor for the
//! formatting paths that need the inner value.

slotmap::new_key_type! {
    pub struct ResourceId;
    pub struct ProfileId;
    pub struct SubId;
    pub struct PromoterId;
}

/// Declare a strongly-typed monotonic correlation token.
///
/// Emits a tuple struct `pub struct $name(u64)` with the derive set
/// every engine-side correlation token wants — `Copy + Clone + Debug +
/// Default + Eq + Ord + Hash + PartialEq + PartialOrd` — plus a
/// [`From<u64>`] impl (the mint surface the engine's `MonotonicCounter`
/// requires) and an inherent [`Self::as_u64`] accessor for formatting
/// paths (env vars, tmp file names).
///
/// The inner `u64` is private — the only construction paths are
/// [`From<u64>`] (the mint surface) and [`Default`] (the never-minted
/// sentinel). Tuple construction (`Name(N)`) is rejected outside this
/// module, so the macro stays the single authority over the type's
/// shape.
///
/// **Default's contract.** `$name::default()` returns `$name(0)`. The
/// engine's `MonotonicCounter::next` pre-increments before constructing,
/// so the first minted id is `$name(1)`; `$name(0)` is reserved as a
/// "never-minted" sentinel — used by test fixtures whose pattern-match
/// path doesn't observe the value (e.g. the bin's
/// `Channels::new()`-bounds tests inject `TimerId::default()` into
/// `Input::TimerExpired` purely to fill the field; the engine routes
/// them to `Diagnostic::StaleTimer` and the test inspects only the
/// diagnostic variant).
///
/// **Cross-space discipline.** The phantom marker on
/// `MonotonicCounter<T>` pins the produced type at compile time, so
/// passing a `MonotonicCounter<TimerId>` where a
/// `MonotonicCounter<CorrelationId>` is expected is a type error. The
/// macro doesn't widen this — it only declares the wrapper.
macro_rules! monotonic_id {
    ($(#[$attr:meta])* $name:ident) => {
        $(#[$attr])*
        #[derive(Copy, Clone, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash)]
        pub struct $name(u64);

        impl From<u64> for $name {
            #[inline]
            fn from(value: u64) -> Self {
                Self(value)
            }
        }

        impl $name {
            /// Inner `u64` representation, exposed for the formatting
            /// paths that need it (env vars, tmp file names). Not a
            /// construction surface — use [`From<u64>`] for that.
            #[must_use]
            #[inline]
            pub const fn as_u64(self) -> u64 {
                self.0
            }
        }
    };
}

monotonic_id! {
    /// Engine-internal timer handle.
    ///
    /// Minted by the engine's `MonotonicCounter` inside its `TimerHeap`;
    /// the heap stores live ids on the owning
    /// [`Profile`](crate::profile::Profile)'s burst slot, and pop
    /// validates the popped entry's id against that slot — cancelled
    /// ids drop silently under lazy invalidation. Unique within a
    /// `TimerHeap`'s lifetime; saturation panics unconditionally
    /// (release-runnable).
    TimerId
}

monotonic_id! {
    /// Per-[`Effect`](crate::effect::Effect) correlation token.
    ///
    /// Engine-monotonic in v1. Pairs each Effect dispatch with the
    /// actuator's
    /// [`Input::EffectComplete`](crate::input::Input::EffectComplete)
    /// echo, and is routed through the actuator's resolver as the
    /// `$SPECTER_CORRELATION` env value and into the per-Effect diff
    /// tmp file name.
    CorrelationId
}

monotonic_id! {
    /// Engine-monotonic probe correlation token.
    ///
    /// Pairs each [`ProbeOp::Probe`](crate::op::ProbeOp::Probe)
    /// emission with the [`ProbeResponse`](crate::op::ProbeResponse)
    /// that answers it; the matching token lives in the engine's
    /// `ProbeChannel.open` map, so off-route responses surface as
    /// [`Diagnostic::StaleProbeResponse`](crate::diag::Diagnostic::StaleProbeResponse)
    /// without touching live burst state.
    ProbeCorrelation
}
