//! Identity tiers and engine correlation tokens.
//!
//! Two families share this module, each with its own discipline:
//!
//! - **Slotmap keys.** [`ResourceId`], [`ProfileId`], [`SubId`],
//!   [`PromoterId`] are generational handles minted by
//!   [`slotmap::SlotMap`]; a stale id looks up to `None`. Reused slot
//!   indices carry distinct generations, so equality is exact identity
//!   over the slot's lifetime, not over the underlying index.
//! - **Monotonic correlation tokens.** [`TimerId`], [`CorrelationId`],
//!   [`ProbeCorrelation`] are plain `u64` wrappers minted by the
//!   engine's `MonotonicCounter`; they pair an engine emission with the
//!   external actor's echo (timer fire, effect completion, probe
//!   response) over the engine's lifetime. They are not slotmap keys —
//!   the per-mint state lives elsewhere (the engine's `TimerHeap`, the
//!   owner state's probe slot, or actuator-side coalesce state), and a
//!   cancelled or completed token is not reusable, only distinguishable.
//!
//! The monotonic family is generated by the module-local
//! `monotonic_id!` macro so the three tokens share one *shape*: a
//! private `u64` field, the conventional correlation-token derive set,
//! an unrestricted [`From<u64>`] construction surface, and an `as_u64`
//! accessor for the formatting paths that need the inner value. The
//! macro owns the shape; value monotonicity is the minting counter's
//! contract, not the type's (see `monotonic_id!`).

slotmap::new_key_type! {
    pub struct ResourceId;
    pub struct ProfileId;
    pub struct SubId;
    pub struct PromoterId;
}

/// Declare a strongly-typed monotonic correlation token.
///
/// Emits a tuple struct `pub struct $name(u64)` deriving the
/// conventional correlation-token set (`Copy`, `Clone`, `Debug`,
/// `Default`, `Eq`, `PartialEq`, `Ord`, `PartialOrd`), a
/// [`From<u64>`] impl, and an inherent [`Self::as_u64`] accessor for
/// formatting paths (env vars, tmp file names).
///
/// **What the macro guarantees: shape, not values.** The inner `u64`
/// is private and tuple construction (`$name(N)`) is rejected outside
/// this module, so the macro is the single authority over the type's
/// *shape* — the struct, the derive set, the construction surface, the
/// accessor. It does *not* constrain the *value*: [`From<u64>`] is
/// intentionally unrestricted (any `u64` maps to an id, with no
/// ordering or uniqueness check). "Ids are minted strictly increasing,
/// never reused" is a runtime **convention of the minting counter**
/// (`MonotonicCounter::next`, the sole minter), *not* a property this
/// type encodes. The only production consumer of [`From<u64>`] is that
/// counter's generic bound (`MonotonicCounter<T: From<u64>>`); every
/// direct `$name::from(n)` call site is a test or `testkit` fixture.
///
/// *Type-honest end-state (deferred).* A `Minted<T>` the counter
/// returns and consumers take by value would drop [`From<u64>`] from
/// the public surface, making "only the counter mints" a type
/// guarantee rather than a convention. Deferred deliberately: it
/// churns every fixture plus the counter bound for an invariant a
/// single-user alpha never violates, and the sole minter is verified.
///
/// **Derive-set rationale.** `Eq`/`PartialEq` is the load-bearing
/// member — response demux and lazy invalidation gate on token
/// *equality* (a stale echo is one whose token no longer equals the
/// in-flight token). `Ord`/`PartialOrd` backs total-order
/// participation: a timer token is the final tie-breaker in the timer
/// heap's `(deadline, profile, id)` order. `Hash` is deliberately
/// **not** derived — every engine-side map keyed by these ids is a
/// `slotmap` or a `BTreeMap` (deterministic iteration is the floor for
/// replay), so a `Hash` impl would be dead surface. `Copy`/`Clone`
/// give cheap value semantics; `Debug` serves diagnostics; `Default`
/// is the never-minted sentinel below.
///
/// **Default's contract.** `$name::default()` returns `$name(0)`. The
/// engine's `MonotonicCounter::next` pre-increments before constructing,
/// so the first minted id is `$name(1)`; `$name(0)` is reserved as a
/// "never-minted" sentinel — used by test fixtures whose pattern-match
/// path doesn't observe the value (e.g. the bin's
/// `Channels::new()`-bounds tests inject `TimerId::default()` into
/// `Input::TimerExpired` purely to fill the field; the engine routes
/// them to `Diagnostic::StaleTimer` and the test inspects only the
/// diagnostic variant).
///
/// **Cross-space discipline.** The phantom marker on
/// `MonotonicCounter<T>` pins the produced type at compile time, so
/// passing a `MonotonicCounter<TimerId>` where a
/// `MonotonicCounter<CorrelationId>` is expected is a type error. The
/// macro doesn't widen this — it only declares the wrapper.
macro_rules! monotonic_id {
    ($(#[$attr:meta])* $name:ident) => {
        $(#[$attr])*
        #[derive(Copy, Clone, Debug, Default, Eq, PartialEq, Ord, PartialOrd)]
        pub struct $name(u64);

        impl From<u64> for $name {
            #[inline]
            fn from(value: u64) -> Self {
                Self(value)
            }
        }

        impl $name {
            /// Inner `u64` representation, exposed for the formatting
            /// paths that need it (env vars, tmp file names). Not a
            /// construction surface — use [`From<u64>`] for that.
            #[must_use]
            #[inline]
            pub const fn as_u64(self) -> u64 {
                self.0
            }
        }
    };
}

monotonic_id! {
    /// Engine-internal timer handle.
    ///
    /// Minted by the engine's `MonotonicCounter` inside its `TimerHeap`;
    /// the heap stores live ids on the owning
    /// [`Profile`](crate::profile::Profile)'s burst slot, and pop
    /// validates the popped entry's id against that slot — cancelled
    /// ids drop silently under lazy invalidation. Unique within a
    /// `TimerHeap`'s lifetime; saturation panics unconditionally
    /// (release-runnable).
    TimerId
}

monotonic_id! {
    /// Per-[`Effect`](crate::effect::Effect) correlation token.
    ///
    /// Engine-monotonic in v1. Pairs each Effect dispatch with the
    /// actuator's
    /// [`Input::EffectComplete`](crate::input::Input::EffectComplete)
    /// echo, and is routed through the actuator's resolver as the
    /// `$SPECTER_CORRELATION` env value and into the per-Effect diff
    /// tmp file name.
    CorrelationId
}

monotonic_id! {
    /// Engine-monotonic probe correlation token.
    ///
    /// Pairs each [`ProbeOp::Probe`](crate::op::ProbeOp::Probe)
    /// emission with the [`ProbeResponse`](crate::op::ProbeResponse)
    /// that answers it; the matching token lives in the owner state's
    /// in-flight probe slot, so off-route responses surface as
    /// [`Diagnostic::StaleProbeResponse`](crate::diag::Diagnostic::StaleProbeResponse)
    /// without touching live burst state.
    ProbeCorrelation
}
